# Generated by Django 3.2 on 2021-07-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '__first__'),
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_register_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_completed_section_id', models.IntegerField(default=0)),
                ('date_created', models.CharField(max_length=255)),
                ('withdraw', models.IntegerField(default=0, max_length=3, null=True)),
                ('approve_date', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register course+', to='teacher.courses')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register user+', to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Course_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('approved_by_teacher', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.courses')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student name+', to='home.user')),
            ],
        ),
    ]
